# Generated by Django 4.2.3 on 2023-08-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_display', models.BooleanField(default=True)),
                ('section_id', models.CharField(max_length=10)),
            ],
        ),
    ]
