# Generated by Django 4.2.3 on 2023-08-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_submenu',
            field=models.BooleanField(default=False),
        ),
    ]
