# Generated by Django 4.2.3 on 2023-08-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_remove_menu_is_submenu_submenu_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.ImageField(upload_to='slider-image')),
                ('slider_title', models.CharField(max_length=100)),
                ('slider_sub_title', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
