# Generated by Django 4.2.3 on 2023-08-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0006_charity'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=150)),
                ('about_sub_title', models.CharField(max_length=150)),
                ('about_description', models.TextField()),
                ('founded_year', models.IntegerField(default=0, max_length=10)),
                ('total_donations', models.IntegerField(default=0.0, max_length=10)),
                ('our_mission_description', models.TextField()),
            ],
        ),
    ]
