# Generated by Django 4.2.3 on 2023-08-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0007_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_image',
            field=models.ImageField(default=1, upload_to='about/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='total_donations',
            field=models.TextField(max_length=20),
        ),
    ]
