# Generated by Django 4.2.3 on 2023-08-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0009_alter_about_total_donations'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='start',
            field=models.IntegerField(default=1),
        ),
    ]
