# Generated by Django 4.2.3 on 2023-08-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0010_about_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='founded_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='about',
            name='total_donations',
            field=models.IntegerField(default=0),
        ),
    ]
