# Generated by Django 4.2.3 on 2023-08-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0013_aboutourmissionlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSectionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about-section-member/')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('facebook_link', models.CharField(max_length=150)),
                ('twitter_link', models.CharField(max_length=150)),
                ('instagram_link', models.CharField(max_length=150)),
            ],
        ),
    ]
