# Generated by Django 4.2.3 on 2023-08-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0014_aboutsectionmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='section_id',
        ),
        migrations.RemoveField(
            model_name='submenu',
            name='sub_menu_page_name',
        ),
        migrations.AddField(
            model_name='menu',
            name='id_or_hef',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submenu',
            name='id_or_hef',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
