# Generated by Django 4.2.3 on 2023-08-01 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0015_remove_menu_section_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_dropdown_menu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='menu',
            field=models.ForeignKey(limit_choices_to={'is_dropdown_menu': True}, on_delete=django.db.models.deletion.CASCADE, to='donation.menu'),
        ),
    ]
