# Generated by Django 4.2.3 on 2023-08-01 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0016_menu_is_dropdown_menu_alter_submenu_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='id_or_hef',
            new_name='id_or_href',
        ),
        migrations.RenameField(
            model_name='submenu',
            old_name='id_or_hef',
            new_name='id_or_href',
        ),
    ]
