# Generated by Django 4.2.3 on 2023-08-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0018_about_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Causes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='causes/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('raised_amount', models.IntegerField(default=0)),
                ('goal_amount', models.IntegerField(default=0)),
                ('raised_amount_percentage', models.IntegerField(default=0)),
            ],
        ),
    ]
