# Generated by Django 4.2.3 on 2023-08-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0020_rename_causes_cause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='raised_amount_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
