# Generated by Django 4.2.3 on 2023-08-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0023_alter_volunteer_volunteer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
