# Generated by Django 4.2.3 on 2023-08-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0025_volunteermember'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteermember',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
