# Generated by Django 4.2.3 on 2023-08-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0028_addnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_letter_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
