# Generated by Django 4.2.3 on 2023-08-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0029_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='HappyCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_image', models.ImageField(upload_to='happy-customer/')),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_quote', models.CharField(max_length=250)),
            ],
        ),
    ]
