# Generated by Django 4.2.3 on 2023-08-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0033_alter_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbar_logo', models.ImageField(upload_to='logo/')),
                ('footer_logo', models.ImageField(upload_to='logo/')),
                ('copyright', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=200)),
                ('facebook_link', models.CharField(max_length=250)),
                ('youtube_link', models.CharField(max_length=250)),
                ('instagram_link', models.CharField(max_length=250)),
                ('twitter_link', models.CharField(max_length=250)),
                ('linkedin_link', models.CharField(max_length=250)),
            ],
        ),
    ]
