# Generated by Django 4.2.3 on 2023-08-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0034_websitesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddDonationAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_amount', models.IntegerField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='AddDonationPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_payment_method', models.CharField(max_length=100)),
            ],
        ),
    ]
